"""
report_generator.py
-------------------
Renders a polished Markdown anomaly report from the outputs of
``log_parser.find_error_block()`` and (optionally)
``llm_explainer.explain_anomaly()``.

Public API
~~~~~~~~~~
    format_report(log_context, explanation) -> str
    generate_report(log_context, explanation, output_path) -> Path
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Severity → emoji badge
# ---------------------------------------------------------------------------

_SEVERITY_BADGE: dict[str, str] = {
    "CRITICAL": "🔴 CRITICAL",
    "ERROR":    "🟠 ERROR",
    "UNKNOWN":  "🟡 UNKNOWN",
}


def _badge(severity: str) -> str:
    return _SEVERITY_BADGE.get(severity.upper(), f"🔵 {severity}")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def format_report(
    log_context: dict,
    explanation: Optional[dict] = None,
) -> str:
    """Build and return the full Markdown report as a string.

    Parameters
    ----------
    log_context:
        Dict returned by ``find_error_block()``.
    explanation:
        Dict returned by ``explain_anomaly()``, or ``None`` when ``--no-llm``
        was requested.

    Returns
    -------
    str
        Complete Markdown document.
    """
    lines: list[str] = []
    L = lines.append  # shorthand

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    severity     = log_context.get("severity", "UNKNOWN")
    log_path     = log_context.get("log_path", "unknown")
    timestamp    = log_context.get("timestamp") or "not detected"
    error_index  = log_context.get("error_line_index")
    total_lines  = log_context.get("total_lines", "?")

    # ------------------------------------------------------------------
    # Title & metadata table
    # ------------------------------------------------------------------
    L("# 🔍 Log Anomaly Report")
    L("")
    L("---")
    L("")
    L("| Field | Value |")
    L("|-------|-------|")
    L(f"| **File** | `{log_path}` |")
    L(f"| **Severity** | {_badge(severity)} |")
    L(f"| **Timestamp** | {timestamp} |")
    if error_index is not None:
        L(f"| **Error location** | Line {error_index} of {total_lines} |")
    L(f"| **Report generated** | {generated_at} |")
    if explanation and explanation.get("model"):
        L(f"| **LLM model** | `{explanation['model']}` |")
    L("")
    L("---")
    L("")

    # ------------------------------------------------------------------
    # Clean-log fast exit
    # ------------------------------------------------------------------
    if not log_context.get("found", False):
        L("> ✅ **No errors or anomalies were detected in this log file.**")
        L("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # AI Analysis section
    # ------------------------------------------------------------------
    has_llm = explanation is not None and not explanation.get("error")
    llm_failed = explanation is not None and bool(explanation.get("error"))

    if has_llm:
        L("## 🤖 AI Analysis")
        L("")
        L("> *Generated by an LLM — review before acting in production.*")
        L("")

        # Summary
        L("### 📋 Summary")
        L("")
        summary = explanation.get("summary", "").strip()
        L(summary if summary else "_No summary was returned by the model._")
        L("")

        # Root cause
        L("### 🎯 Root Cause")
        L("")
        root_cause = explanation.get("root_cause", "").strip()
        L(root_cause if root_cause else "_No root cause analysis was returned._")
        L("")

        # Why it happened
        L("### 🔎 Why It Happened")
        L("")
        why = explanation.get("why_it_happened", "").strip()
        L(why if why else "_No contextual explanation was returned._")
        L("")

        # Suggested fix  ← key field that was missing presentation before
        L("### 🛠️ Suggested Fix")
        L("")
        fix = explanation.get("suggested_fix", "").strip()
        L(fix if fix else "_No suggested fix was returned._")
        L("")

        # Prevention
        L("### 🛡️ Prevention")
        L("")
        prevention = explanation.get("prevention", "").strip()
        L(prevention if prevention else "_No prevention tips were returned._")
        L("")

        L("---")
        L("")

    elif llm_failed:
        L("## 🤖 AI Analysis")
        L("")
        L(f"> ⚠️ **LLM explanation unavailable.**  ")
        L(f"> {explanation['error']}")  # type: ignore[index]
        L("")
        L("---")
        L("")

    else:
        # --no-llm path
        L("## 🤖 AI Analysis")
        L("")
        L("> ⏭️ *LLM analysis was skipped (`--no-llm` flag).*")
        L("")
        L("---")
        L("")

    # ------------------------------------------------------------------
    # Raw error block
    # ------------------------------------------------------------------
    L("## 🚨 Raw Error Block")
    L("")
    error_block = log_context.get("error_block", [])
    L("```log")
    L("\n".join(error_block) if error_block else "(empty)")
    L("```")
    L("")

    # ------------------------------------------------------------------
    # Context windows
    # ------------------------------------------------------------------
    context_before = log_context.get("context_before", [])
    context_after  = log_context.get("context_after",  [])

    if context_before:
        L("## 📜 Context Before Error")
        L("")
        L(f"*{len(context_before)} line(s) preceding the error.*")
        L("")
        L("```log")
        L("\n".join(context_before))
        L("```")
        L("")

    if context_after:
        L("## 📜 Context After Error")
        L("")
        L(f"*{len(context_after)} line(s) following the error.*")
        L("")
        L("```log")
        L("\n".join(context_after))
        L("```")
        L("")

    # ------------------------------------------------------------------
    # Collapsible raw LLM response (for debugging / audit trail)
    # ------------------------------------------------------------------
    if has_llm and explanation.get("raw_llm_response"):  # type: ignore[union-attr]
        L("<details>")
        L("<summary>🗒️ Raw LLM response (click to expand)</summary>")
        L("")
        L("```")
        L(explanation["raw_llm_response"])  # type: ignore[index]
        L("```")
        L("")
        L("</details>")
        L("")

    # ------------------------------------------------------------------
    # Footer
    # ------------------------------------------------------------------
    L("---")
    L("")
    L("*Generated by [log-anomaly-explainer](https://github.com/your-org/log-anomaly-explainer)*")
    L("")

    return "\n".join(lines)


def generate_report(
    log_context: dict,
    explanation: Optional[dict] = None,
    output_path: str = "anomaly_report.md",
) -> Path:
    """Render and write the Markdown report to *output_path*.

    Parameters
    ----------
    log_context:
        Dict returned by ``find_error_block()``.
    explanation:
        Dict returned by ``explain_anomaly()``, or ``None``.
    output_path:
        Destination file path.  Parent directories are created if needed.

    Returns
    -------
    Path
        Resolved absolute path of the written report file.
    """
    dest = Path(output_path).resolve()
    dest.parent.mkdir(parents=True, exist_ok=True)

    content = format_report(log_context, explanation)
    dest.write_text(content, encoding="utf-8")
    return dest
